.PHONY: all clean test
all: 
	$(MAKE) -C src all
clean:
	$(MAKE) -C src clean
libtb.o:
	$(MAKE) -C src libtb.o
libminsearch.o:
	$(MAKE) -C src libminsearch.o
libioparser.o:
	$(MAKE) -C src libioparser.o
libclparser.o:
	$(MAKE) -C src libclparser.o
libfmblas.o:
	$(MAKE) -C src libfmblas.o
librndgen.o:
	$(MAKE) -C src librndgen.o
libtoolbox.a:
	$(MAKE) -C src libtoolbox.a
matrix-test:
	$(MAKE) -C src matrix-test
matconv:
	$(MAKE) -C src matconv
io-test:
	$(MAKE) -C src io-test
gendist:
	$(MAKE) -C src gendist
autocorr:
	$(MAKE) -C src autocorr
crosscorr:
	$(MAKE) -C src crosscorr
trajworks:
	$(MAKE) -C src trajworks
histogram:
	$(MAKE) -C src histogram
ndhistogram:
	$(MAKE) -C src ndhistogram
pmult:
	$(MAKE) -C src pmult
gaussmix:
	$(MAKE) -C src gaussmix